### ISSUE TITLE
I don't know if this sheet music is easy to convert.

### ISSUE THREAD

**Issue by xp12047** [Jemtaly/ProjectMu#1]
![Screenshot_20220922_190316_com android gallery3d_edit_660137970077394](https://user-images.githubusercontent.com/56335408/191730994-f5528712-c283-4f97-ac2a-4de38f09f344.jpg)
This tool you made is awesome!  But I have no knowledge of music theory at all.  Wondering if the score on the picture can be converted into audio with this tool?

**Comment by Jemtaly** [comment]
Hello, thanks for your like, I've converted this score to NMN file format for you. You can use this tool to generate audio with the following command:

```
mu 飞雪玉花.nmn -o 飞雪玉花 -t4
```

*\* I recommend using the `-t4` parameter because it makes the resulting audio tone sound like a flute, which I think is appropriate for this tune.*

**Comment by xp12047** [comment]
> 您好，感谢您的喜欢，我已将此乐谱打入本工具所需的文件格式：[飞雪玉花.txt](https://github.com/Jemtaly/ProjectMu/files/9630229/default.txt)。您可以使用此工具通过以下命令生成音频：
> 
> ```
> mu 飞雪玉花.txt -o 飞雪玉花.wav -t4
> ```
> 
> _* 我建议使用该`-t4`参数，因为它使生成的音频听起来像长笛，我认为这适合这首曲子。_

Wow!  Thank you thank you, great!  Can you tell me how you converted these?

**Comment by xp12047** [comment]
> 您好，感谢您的喜欢，我已将此乐谱打入本工具所需的文件格式：[飞雪玉花.txt](https://github.com/Jemtaly/ProjectMu/files/9630229/default.txt)。您可以使用此工具通过以下命令生成音频：
> 
> ```
> mu 飞雪玉花.txt -o 飞雪玉花.wav -t4
> ```
> 
> _* 我建议使用该`-t4`参数，因为它使生成的音频听起来像长笛，我认为这适合这首曲子。_

uh, the warning doesn't matter, does it?  
![mmexport1663901559739](https://user-images.githubusercontent.com/56335408/191883927-82778061-c8e2-49c4-9b48-be1be839dd7c.png)

**Comment by xp12047** [comment]
> Hi, thank you for liking it, I've typed this music score into the file format required for this tool for you: [飞雪玉花.txt](https://github.com/Jemtaly/ProjectMu/files/9630229/default.txt). You can use this tool to generate audio with the following command:
> 
> ```
> mu 飞雪玉花.txt -o 飞雪玉花.wav -t4
> ```
> 
> _* I recommend using the `-t4` parameter because it makes the resulting audio tone sound like a flute, which I think is appropriate for this piece._

![src=http___www sooopu com_Member_SooopuEdit1_uploadfile_201008_20100819214131424 jpg refer=http___www sooopu_edit_30411938016191](https://user-images.githubusercontent.com/56335408/191915873-b6ced296-4b62-44aa-9e17-279c431862c4.jpg)
像一开始的3553 直接在数字中间加上空格就行是吗？3 5 5 3这样是对的嘛？

**Comment by Jemtaly** [comment]
> > 您好，感谢您的喜欢，我已将此乐谱打入本工具所需的文件格式：[飞雪玉花.txt](https://github.com/Jemtaly/ProjectMu/files/9630229/default.txt)。您可以使用此工具通过以下命令生成音频：
> > ```
> > mu 飞雪玉花.txt -o 飞雪玉花.wav -t4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _* 我建议使用该`-t4`参数，因为它使生成的音频听起来像长笛，我认为这适合这首曲子。_
> 
> uh, the warning doesn't matter, does it? ![mmexport1663901559739](https://user-images.githubusercontent.com/56335408/191883927-82778061-c8e2-49c4-9b48-be1be839dd7c.png)

嗯，可以忽略。



> > Hi, thank you for liking it, I've typed this music score into the file format required for this tool for you: [飞雪玉花.txt](https://github.com/Jemtaly/ProjectMu/files/9630229/default.txt). You can use this tool to generate audio with the following command:
> > ```
> > mu 飞雪玉花.txt -o 飞雪玉花.wav -t4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _* I recommend using the `-t4` parameter because it makes the resulting audio tone sound like a flute, which I think is appropriate for this piece._
> 
> ![src=http___www sooopu com_Member_SooopuEdit1_uploadfile_201008_20100819214131424 jpg refer=http___www sooopu_edit_30411938016191](https://user-images.githubusercontent.com/56335408/191915873-b6ced296-4b62-44aa-9e17-279c431862c4.jpg) 像一开始的3553 直接在数字中间加上空格就行是吗？3 5 5 3这样是对的嘛？

对，不过其实空格的作用只是方便阅读，程序会无视曲谱中的空格，所以在输入的时候省略也可以。

**Comment by xp12047** [comment]
> > > 您好，感谢您的喜欢，我已将此乐谱打入本工具所需的文件格式：[飞雪玉花.txt](https://github.com/Jemtaly/ProjectMu/files/9630229/default.txt)。您可以使用此工具通过以下命令生成音频：
> > > ```
> > > mu 飞雪玉花.txt -o 飞雪玉花.wav -t4
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > _* 我建议使用该`-t4`参数，因为它使生成的音频听起来像长笛，我认为这适合这首曲子。_
> > 
> > 
> > uh, the warning doesn't matter, does it?
> > ![mmexport1663901559739](https://user-images.githubusercontent.com/56335408/191883927-82778061-c8e2-49c4-9b48-be1be839dd7c.png)
> 
> 嗯，可以忽略。
> 
> > > Hi, thank you for liking it, I've typed this music score into the file format required for this tool for you: [飞雪玉花.txt](https://github.com/Jemtaly/ProjectMu/files/9630229/default.txt). You can use this tool to generate audio with the following command:
> > > ```
> > > mu 飞雪玉花.txt -o 飞雪玉花.wav -t4
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > _* I recommend using the `-t4` parameter because it makes the resulting audio tone sound like a flute, which I think is appropriate for this piece._
> > 
> > 
> > ![src=http___www sooopu com_Member_SooopuEdit1_uploadfile_201008_20100819214131424 jpg refer=http___www sooopu_edit_30411938016191](https://user-images.githubusercontent.com/56335408/191915873-b6ced296-4b62-44aa-9e17-279c431862c4.jpg)
> > 像一开始的3553 直接在数字中间加上空格就行是吗？3 5 5 3这样是对的嘛？
> 
> 对，不过其实空格的作用只是方便阅读，程序会无视你在曲谱中输入的空格，所以就算省略掉直接写成 `3553` 也完全可以。在我给你的文件中除了第一行以外所有空格都是可以省略的。

明白，谢谢😊。还有像下图那个6和7上方的半括号可以表示出来嘛？还是不用表示出来，如果表示出来的话该怎么表示？  
![Screenshot_20220923_194254](https://user-images.githubusercontent.com/56335408/191958156-8da63986-acc2-4f2f-985e-860b80ecc7d7.jpg)

**Comment by Jemtaly** [comment]
> 明白，谢谢😊。还有像下图那个6和7上方的半括号可以表示出来嘛？还是不用表示出来，如果表示出来的话该怎么表示？
> ![Screenshot_20220923_194254](https://user-images.githubusercontent.com/56335408/191958156-8da63986-acc2-4f2f-985e-860b80ecc7d7.jpg)

两个不同音上的弧线表示圆滑线，由于这个程序目前还不支持圆滑音，所以不需要表示出来。

但如果是两个或多个相同音符的话（比如最后的两个 6）那么弧线就表示延音线，这时第一个以后的音符需要用 `,` 代替。（两个相同音符的意思是说它们的数字、数字后可能标注的升降符号（如 `#` 和 `b`）、音符上的高音点和音符下的低音点（即 `^` 和 `v`）完全相同）

**Comment by xp12047** [comment]
> > 明白，谢谢😊。还有像下图那个6和7上方的半括号可以表示出来嘛？还是不用表示出来，如果表示出来的话该怎么表示？
> > ![Screenshot_20220923_194254](https://user-images.githubusercontent.com/56335408/191958156-8da63986-acc2-4f2f-985e-860b80ecc7d7.jpg)
> 
> 两个不同音上的弧线表示圆滑线，由于这个程序目前还不支持圆滑音，所以不需要表示出来。
> 
> 但如果是两个或多个相同音符的话（比如最后的两个 6）那么弧线就表示延音线，这时第一个以后的音符需要用 `,` 代替。（两个相同音符的意思是说它们的数字、数字后可能标注的升降符号（如 `#` 和 `b`）、音符上的高音点和音符下的低音点（即 `^` 和 `v`）完全相同）

明白 谢谢😊

**Comment by Jemtaly** [comment]
> 大大这个图中的 :||和||:是不是没有办法表示？还有那种2在左上角下面有个3的 不知道该怎么表示。

:|| 和 ||: 还有乐谱里的 D.S 都是反复记号，如果完全不懂乐理的话解释起来比较困难，简单起见你可以直接把从歌词“我的心”以后一直到最后一个“中”以前的那些小节全省略掉，或者把你打出来的文件发给我，我帮你改一下。

**Comment by xp12047** [comment]
> > 大大这个图中的 :||和||:是不是没有办法表示？还有那种2在左上角下面有个3的 不知道该怎么表示。
> 
> :|| 和 ||: 还有乐谱里的 D.S 都是反复记号，如果完全不会读谱的话解释起来比较困难，简单起见你可以直接把从歌词“我的心”以后一直到最后一个“中”以前的那些小节全省略掉，或者把你打出来的文件发给我，我帮你改一下。

[孤城.txt](https://github.com/Jemtaly/ProjectMu/files/9639058/default.txt)
谢谢！有劳了。

**Comment by xp12047** [comment]
抄这个简谱我抄了好久😔。抄得头晕乎乎的😔我边抄边想你那些谱子咋抄的。。
但我依然很开心有你开发的这个工具，让我更快的了解一些乐理基础。谢谢😊

**Comment by xp12047** [comment]
在你这个工具之前我在用另外一种类似的https://github.com/allthemusicllc/atm-cli  
就是这个工具让俺觉得挺有意思的，但是俺不会用。更看不懂那个字母加数字的表达方式。只能抄例子体验体验😔到网上搜谱子又都是数字的那种。后来有幸搜到你的这个。算是找对了。😊

**Comment by Jemtaly** [comment]
你好，这是修改后的谱子，那些标注在左上角的倚音表示起来比较麻烦，所以我省掉了。
[default.txt](https://github.com/Jemtaly/ProjectMu/files/9639963/default.txt)

**Comment by xp12047** [comment]
> 你好，这是修改后的谱子：[孤城.txt](https://github.com/Jemtaly/ProjectMu/files/9639963/default.txt)
> 
> 记录当前的逻辑比较复杂度，可以这样多次手动乐谱分解成多个部分，然后自动显示我通过进程执行顺序的方式。功能）另外，那些标注在左上角的小音符（音）可以表示但比较麻烦，所以我省掉了。
> 
> 我还修改了弧谱里几个抄错的地方，比如漏掉的低音乐点和下划线的，另外像你这样的，两个同样的音调用线连起来的情况，第二个音需要用`,`代替：
> 
> <img alt="屏幕截图 2022-09-25 111850" width="59" src="https://user-images.githubusercontent.com/83796250/192127172-36defe41-b6ac-4703-98d9-e54593c636e8.png">
> 
> ```
> 7./1^// ,/7/
> ```

谢谢谢！那个小音符有时间可以给举例说明下嘛？

**Comment by xp12047** [comment]
> 你好，这是修改后的谱子：[孤城.txt](https://github.com/Jemtaly/ProjectMu/files/9639963/default.txt)
> 
> 记录当前的逻辑比较复杂度，可以这样多次手动乐谱分解成多个部分，然后自动显示我通过进程执行顺序的方式。功能）另外，那些标注在左上角的小音符（音）可以表示但比较麻烦，所以我省掉了。
> 
> 我还修改了弧谱里几个抄错的地方，比如漏掉的低音乐点和下划线的，另外像你这样的，两个同样的音调用线连起来的情况，第二个音需要用`,`代替：
> 
> <img alt="屏幕截图 2022-09-25 111850" width="59" src="https://user-images.githubusercontent.com/83796250/192127172-36defe41-b6ac-4703-98d9-e54593c636e8.png">
> 
> ```
> 7./1^// ,/7/
> ```

的确比一开始生成的好太多了😁，谢谢谢，最后为什么是123456啊？简谱上没看到有。  
最后在你有时间的时候能不能给推荐些基础乐理学习链接，我找了几个不好。

**Comment by Jemtaly** [comment]
> 的确比一开始生成的好太多了😁，谢谢谢，最后为什么是123456啊？简谱上没看到有。 最后在你有时间的时候能不能给推荐些基础乐理学习链接，我找了几个不好。

<img width="562" alt="image" src="https://user-images.githubusercontent.com/83796250/192130457-27be127c-dffb-43de-a18f-70ce05584a73.png">

最后一行的数字不是音符，是乐谱各个部分的演奏顺序，我为了表示反复记号，把乐谱分成了六个部分。乐理的话其实不需要学习得很深，在网上找点简谱的教程看看就行。

**Comment by xp12047** [comment]
> > 的确比一开始生成的好太多了😁，谢谢谢，最后为什么是123456啊？简谱上没看到有。 最后在你有时间的时候能不能给推荐些基础乐理学习链接，我找了几个不好。
> 
> <img alt="image" width="562" src="https://user-images.githubusercontent.com/83796250/192130457-27be127c-dffb-43de-a18f-70ce05584a73.png">
> 
> 最后一行的数字不是音符，是乐谱各个部分的演奏顺序，我为了表示反复记号，把乐谱分成了六个部分。乐理的话其实不需要学习得很深，在网上找点简谱的教程看看就行。

好，谢谢！这个程序都支持哪类简谱呢？下图那种好表示嘛？
![01-724x1024](https://user-images.githubusercontent.com/56335408/192131237-52371797-1293-4bcf-a935-7ce223c547df.png)

**Comment by Jemtaly** [comment]
不支持像这样有多个声部的乐谱（即这种上下两行用大括号括起来的），但你可以单独抄写其中一个声部，一般来说是最高的音决定乐曲的主旋律，所以你只要抄写每两行里的上面那一行就好了。（如果遇到上面一行中也有上下两个叠起来的音的情况那么就只抄摞在上面的那个音）

<img width="238" alt="image" src="https://user-images.githubusercontent.com/83796250/192134351-3461cbdc-47d5-4cc9-aadc-08b5cd4df6c5.png">

另外像图里这样用弧线括起来，且弧线上标注着数字的是 n 连音（写着 3 就是三连音），表示方式是 `[n:弧线里的内容]`，如上图左下角那组即写为 `[3:6v/3/6/]`

**Comment by xp12047** [comment]
> 不支持像这样有所以部的乐谱（即这种上下两行用大括号括起来的），但你可以单独抄写一个声部，一般来说曲子是最高音乐的多个主旋律，你（如果上面每一行也有上下两行重叠在一起的声音的情况，那么就抄写在上面的那个声音就好了）
> 
> <img alt="图片" width="238" src="https://user-images.githubusercontent.com/83796250/192134351-3461cbdc-47d5-4cc9-aadc-08b5cd4df6c5.png">
> 
> 另外像图里这样用弧线括起来，而且弧线那组标注数字是n连音（写着3三连音），表示是`[n:弧线里的内容]`，如上图左下角即写为`[3:6v/3/6/]`

好，谢谢😊
